BASE_URL = '0.0.0.0'

SQLALCHEMY_DATABASE_URI = 'postgres://postgres:ankur17aug@localhost:5432/homesecurity'

SECRET_KEY = 'secret_key'

#Item_Id:
ITEM_LAYS = 1

LOGGED_IN = 1
LOGGED_OUT = 2

CODE_SOMETHING_WENT_WRONG = 2
CODE_SUCCESS = 3
CODE_WRONG_VALUE = 5
CODE_USER_NOT_REGISTERED = 4